patterns:
  - "*.json"
  - "*.yaml"
  - "*.yml"

format: json

customCatalog:
  schemas:
    - name: "Ammo"
      description: "Schema for validating Ammo YAML fragments"
      fileMatch: ["src/packs/**/ammo.*.yaml"]
      location: "schema/ammo.json"
    - name: "Armor"
      description: "Schema for validating Armor YAML fragments"
      fileMatch: ["src/packs/**/armor.*.yaml"]
      location: "schema/armor.json"
    - name: "Clothing"
      description: "Schema for validating Clothing YAML fragments"
      fileMatch: ["src/packs/**/clothing.*.yaml"]
      location: "schema/clothing.json"
    - name: "Critical Injuries"
      description: "Schema for validating Critical Injury YAML fragments"
      fileMatch: ["src/packs/**/criticalinjury.*.yaml"]
      location: "schema/criticalInjury.json"
    - name: "Cyberdeck"
      description: "Schema for validating Cyberdeck YAML fragments"
      fileMatch: ["src/packs/**/cyberdeck*.yaml"]
      location: "schema/cyberdeck.json"
    - name: "Cyberware"
      description: "Schema for validating Cyberware-Items YAML fragments"
      fileMatch: ["src/packs/**/cyberware.*.yaml"]
      location: "schema/cyberware-items.json"
    - name: "Drugs"
      description: "Schema for validating Drug YAML fragments"
      fileMatch: ["src/packs/drugs/drug.*.yaml"]
      location: "schema/drugs.json"
    - name: "Gear"
      description: "Schema for validating Gear YAML fragments"
      fileMatch: ["src/packs/**/gear.*.yaml"]
      location: "schema/gear.json"
