_id: g5S5E8UG1QJ4yFsp
effects: []
flags:
  core: {}
folder: null
img: systems/cyberpunk-red-core/icons/compendium/default/Default_Role.svg
name: Netrunner
ownership:
  default: 0
sort: 0
system:
  abilities: []
  addRoleAbilityRank: true
  bonusRatio: 1
  bonuses: []
  description:
    chat: ''
    unidentified: ''
    value: >-
      <p>Master hackers who put themselves at risk as they jack into cyberspace
      to download secrets and infiltrate networks.</p>
  favorite: false
  hasRoll: true
  isSituational: false
  mainRoleAbility: Interface
  onByDefault: false
  rank: 4
  skill: '--'
  source: Pg. 147
  stat: '--'
  tags: []
  universalBonuses: []
type: role
