/* eslint-disable no-param-reassign  */
import Datastore from "nedb";
import YAML from "js-yaml";
import fs from "fs-extra";
import log from "fancy-log";
import path from "path";
import sanitize from "sanitize-filename";

import * as config from "./config.mjs";
import { DEBUG, SYSTEM_FILE, SYSTEM_NAME } from "./constants.mjs";

const destFolder = path.resolve(config.dataPath);
const srcFolder = "src";

// Make sure we have a nice filename
function _cleanFileName(data) {
  if (DEBUG) {
    log("DEBUG: Cleaning Filename");
  }
  return sanitize(data)
    .replace(/\u2211/g, "")
    .replace(/\u03B2/g, "")
    .replace(/[‘’]/gu, "")
    .replace(/[“”]/gu, "")
    .replace(/['"]/g, "")
    .replace(/[()]/g, "")
    .replace(/[&]/g, "and")
    .replace(/ /g, ".")
    .replace(/\.\./g, ".")
    .replace(/\.-\./g, ".")
    .toLowerCase();
}

// Removes invisible whitespace chars and normalises single and double-quotes.
function _cleanString(str) {
  return str
    .replace(/\u2060/gu, "")
    .replace(/[‘’]/gu, "'")
    .replace(/[“”]/gu, '"');
}

// Remove unwanted flags, permission, and other data
function _cleanPackData(data) {
  // These could probably be generated by src/template.json
  const itemsWithEffects = [
    "armor",
    "clothing",
    "cyberware",
    "criticalInjury",
    "drug",
    "gear",
    "program",
    "weapon",
  ];

  const containerItems = [
    "armor",
    "clothing",
    "cyberware",
    "cyberdeck",
    "gear",
    "itemUpgrade",
    "vehicle",
    "weapon",
  ];

  const installableItems = ["cyberware", "cyberdeck", "itemUpgrade", "program"];

  // Delete Foundry keys we don't need
  if ("_stats" in data) {
    delete data._stats;
  }
  if ("folder" in data) {
    delete data.folder;
  }
  if ("origin" in data) {
    delete data.origin;
  }
  if ("ownership" in data) {
    delete data.ownership;
  }
  if ("sort" in data) {
    delete data.sort;
  }
  if ("permission" in data) {
    delete data.permission;
  }

  // If an item should have effects
  if (itemsWithEffects.includes(data.type)) {
    // system.revealed should always be true
    data.system.revealed = true;

    // system.usage should always be one of:
    // 'equipped', 'installed', 'rezzed', 'snorted', or 'toggled'
    // never 'carried'
    // use 'equipped' as the default

    // If we're missing the usage key, set it to 'equipped'
    if ("usage" in data.system === false) {
      data.system.usage = "equipped";
    }
    // If system.usage is set to 'owned' set it to 'equipped' instead
    if (data.system.usage === "owned") {
      data.system.usage = "equipped";
    }
  } else {
    delete data.effects;
    delete data.system?.revealed;
    delete data.system?.usage;
  }

  //
  // !! START Cleanup old packs !!!
  //
  // These can be removed once we have the JSONSchema MR merged

  // Not all compendia have 'system' keys
  if ("system" in data) {
    // Fix general issues with keys in 'system'

    // If an item is a container, make sure it has the right keys
    if (containerItems.includes(data.type)) {
      if ("installedItems" in data.system === false) {
        data.system.installedItems = {
          allowed: true,
          allowedTypes: [],
          list: [],
          slots: 0,
          usedSlots: 0,
        };
      }
    }

    // system.description should be an object
    if ("description" in data.system) {
      if (typeof data.system.description === "string") {
        data.system.description = {
          value: "",
          chat: "",
          unidentified: "",
        };
      }
    }

    // Installable items
    if (installableItems.includes(data.type)) {
      // If we don't have a size, set it to 1
      if ("size" in data.system === false) {
        data.system.size = 1;
      }
      // If we don't have 'installLocation'
      if ("installLocation" in data.system === false) {
        // check if we have an old 'install' key and set it to that, else set to
        // 'notApplicable'
        if ("install" in data.system) {
          data.system.installLocation = data.system.install;
        } else {
          data.system.installLocation = "notApplicable";
        }
      }
      // Defaults
      data.system.isInstalled = false;
      data.system.installedIn = "";
    }

    // system.price.category should not exist
    if ("price" in data.system) {
      if ("category" in data.system.price) {
        delete data.system.price.category;
      }
    }

    // Clean up per item type issues

    // Ammo
    if (data.type === "ammo") {
      // Some ammo was missing ablation value, set it to 1
      if ("ablationValue" in data.system === false) {
        data.system.ablationValue = 1;
      }
    }

    // Cyberdeck
    if (data.type === "cyberdeck") {
      if ("system" in data) {
        // cyberdecks don't stack
        if ("amount" in data.system) {
          delete data.system.amount;
        }
      }
    }

    // Cyberware
    if (data.type === "cyberware") {
      // Set any empty strings to '0'. Yes a string, it's usually a dice roll
      if ("humanityLoss" in data.system) {
        if (data.system.humanityLoss.roll === "")
          data.system.humanityLoss.roll = "0";
      }

      if ("amount" in data.system) {
        delete data.system.amount;
      }

      // Set isWeapon to an actual bool
      if ("isWeapon" in data.system) {
        // fix string to bool
        if (data.system.isWeapon === "false") {
          data.system.isWeapon = false;
        }
        if (data.system.isWeapon === "true") {
          data.system.isWeapon = true;
        }
      }
      // Add in new keys if missing
      // If we're missing the 'isFoundational' key set to false
      if ("isFoundational" in data.system === false) {
        data.system.isFoundational = false;
      }

      // Set to an empty string instead of null
      if (data.system.dvTable === null) {
        data.system.dvTable = "";
      }
    }

    if (data.type === "itemUpgrade") {
      if ("equipped" in data.system) {
        delete data.system.equipped;
      }
    }

    // Setup programs properly
    if (data.type === "program") {
      // If we're missing 'size' set to 1
      if ("size" in data.system === false) {
        data.system.size = 1;
      }
      if (data.system.damage.blackIce === "") {
        data.system.damage.blackIce = "0";
      }
      if (data.system.damage.standard === "") {
        data.system.damage.standard = "0";
      }
    }

    // Setup role properly
    if (data.type === "role") {
      // loop over abilities
      data.system.abilities.forEach((ability) => {
        // convert string to number
        ability.multiplier = parseFloat(ability.multiplier);
      });
    }

    // Clean up old/unused keys
    if ("allowedUsage" in data.system) {
      delete data.system.allowedUsage;
    }
    if ("availableSlots" in data.system) {
      delete data.system.availableSlots;
    }
    if ("charges" in data.system) {
      delete data.system.charges;
    }
    if ("effects" in data.system) {
      delete data.system.effects;
    }
    if ("hasOptionalSlots" in data.system) {
      delete data.system.hasOptionalSlots;
    }
    if ("install" in data.system) {
      delete data.system.install;
    }
    if ("installedOptionSlots" in data.system) {
      delete data.system.installedOptionSlots;
    }
    if ("isConcealed" in data.system) {
      delete data.system.isConcealed;
    }
    if ("isGM" in data.system) {
      delete data.system.isGM;
    }
    if ("isOwned" in data.system) {
      delete data.system.isOwned;
    }
    if ("optionSlots" in data.system) {
      delete data.system.optionSlots;
    }
    if ("optionalIds" in data.system) {
      delete data.system.optionalIds;
    }
    if ("permission" in data.system) {
      delete data.system.permission;
    }
    if ("quality" in data.system) {
      delete data.system.quality;
    }
    if ("slotSize" in data.system) {
      delete data.system.slotSize;
    }
    if ("slots" in data.system) {
      delete data.system.slots;
    }
    if ("tags" in data.system) {
      delete data.system.tags;
    }
    if ("upgrade" in data.system) {
      delete data.system.upgrade;
    }
    // For some reason we are using non camelCase for this key. delete the
    // camelCase version of this key
    if ("attackMod" in data.system) {
      delete data.system.attackMod;
    }
  }

  //
  // !! END Cleanup old packs !!!
  //

  // Sanitize strings
  if (data.name) data.name = _cleanString(data.name);
  if (data.label) data.label = _cleanString(data.label);

  if (data.system?.description?.value) {
    data.system.description.value = _cleanString(data.system.description.value);
  }

  // Remove empty values from system.ammoVariety
  if (data.type === "weapon") {
    const ammo = data.system.ammoVariety;
    const result = ammo.filter((i) => i !== "");
    data.system.ammoVariety = result;
  }

  // Ensure system.amount is an int
  if (data.system?.amount) {
    data.system.amount = parseInt(data.system.amount, 10);
  }

  // Ensure system.price.market is an int
  if (data.system?.price) {
    data.system.price.market = parseInt(data.system.price.market, 10);
  }

  // Ensure system.humanityLoss.static is an int
  if (data.system?.humanityLoss?.static) {
    data.system.humanityLoss.static = parseInt(
      data.system.humanityLoss.static,
      10
    );
  }

  // Run the function over any effects
  if (data.effects) {
    data.effects.forEach((i) => _cleanPackData(i));
  }
  return data;
}

// Export from Foundry Packs to fragments
// Loop over each pack.db in `dataDir/packs` and create a directory for install
// in `src/packs`
async function extPacks() {
  return new Promise((cb) => {
    log("Extracting Packs...");
    const fragmentDir = path.resolve(srcFolder, "packs");
    const packsDir = path.resolve(destFolder, "packs");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    if (fs.existsSync(packsDir)) {
      packs.forEach((pack) => {
        const packName = pack.name;
        const packPath = path.resolve(packsDir, `${packName}.db`);
        if (DEBUG) {
          log(`DEEBUG: Processing ${packName}`);
        }

        // Check the pack exists
        if (fs.existsSync(packPath)) {
          // Check if the output dir exists, if not create it
          if (!fs.existsSync(path.join(fragmentDir, packName))) {
            fs.mkdirSync(path.join(fragmentDir, packName), { mode: 0o755 });
          }

          // Load the pack into nedb
          const db = new Datastore({ filename: packPath, autoload: true });
          db.loadDatabase();

          // Find each entry and output to YAML file in `src/packs`
          db.find({}, (err, entries) => {
            entries.forEach((entry) => {
              const itemName =
                typeof entry.type !== "string"
                  ? _cleanFileName(entry.name)
                  : `${_cleanFileName(entry.type)}.${_cleanFileName(
                      entry.name
                    )}`;
              if (DEBUG) {
                log(`Processing ${itemName}`);
              }
              const data = _cleanPackData(entry);
              const output = YAML.dump(
                data,
                { sortKeys: true, quotingType: '"' },
                2
              );
              fs.writeFileSync(
                path.join(fragmentDir, packName, `${itemName}.yaml`),
                output,
                { mode: 0o644 }
              );
            });
          });
        } else {
          throw Error(`${packPath} does not exist`);
        }
      });
    } else {
      throw Error(`${packsDir} does not exist.`);
    }
    log("Finished Extracting Packs...");
    cb();
  });
}

async function genPacks() {
  return new Promise((cb) => {
    log("Generating Packs...");
    const fragmentDir = path.resolve(srcFolder, "packs");
    const packsDir = path.resolve(destFolder, "packs");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    // Create the packs dir if it doesn't exist.
    if (!fs.existsSync(packsDir)) {
      fs.mkdirSync(packsDir);
    }

    packs.forEach((pack) => {
      const packName = pack.name;
      const packPath = path.resolve(packsDir, `${packName}.db`);
      if (DEBUG) {
        log(`DEBUG: Processing ${packName}`);
      }

      // If the fragment dir exists, do stuff, else error
      if (fs.existsSync(path.join(fragmentDir, packName))) {
        const fragments = fs.readdirSync(path.join(fragmentDir, packName));
        const db = fs.createWriteStream(packPath, { flags: "a", mode: 0o644 });
        const data = [];

        // Loop over each file
        fragments.forEach((fragment) => {
          if (DEBUG) {
            log(`DEBUG: Processing ${packName}/${fragment}`);
          }
          const fragmentPath = path.join(fragmentDir, packName, fragment);
          const entry = YAML.load(fs.readFileSync(fragmentPath), "UTF-8");

          _cleanPackData(entry);
          data.push(entry);
        });
        // Sort the pack
        data.sort((lhs, rhs) => (lhs._id > rhs._id ? 1 : -1));
        // Write each entry to the pack
        for (const entry of data) {
          db.write(`${JSON.stringify(entry)}\n`);
        }
        db.end();
      } else {
        throw Error(`${path.join(fragmentDir, packName)} does not exist`);
      }
    });
    log("Finished Generating Packs...");
    cb();
  });
}

// Export from Foundry Packs to Babele files for translation
// Loop over each pack.db in `dataDir/packs` and create babele file for
// translation using crowdin
async function genPacksBabele() {
  return new Promise((cb) => {
    log("Generating Babele Files...");
    // We only care about translating certian pack types
    const translatedPacks = ["Item", "RollTable"];

    const fragmentDir = path.resolve(srcFolder, "packs");
    const babeleDir = path.resolve(srcFolder, "babele", "en");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    // Create the packs dir if it doesn't exist.
    if (!fs.existsSync(babeleDir)) {
      fs.mkdirSync(babeleDir);
    }

    packs.forEach((pack) => {
      if (translatedPacks.includes(pack.type)) {
        const packName = pack.name;
        const packFileName = packName;
        const packLabel = pack.label;
        const packType = pack.type;
        const babelePath = path.resolve(
          babeleDir,
          `${SYSTEM_NAME}.${packFileName}.json`
        );
        if (DEBUG) {
          log(`DEBUG: Processing ${packName}`);
        }

        const packData = {
          label: packLabel,
          entries: {},
        };

        // If the fragment dir exists, do stuff, else error
        if (fs.existsSync(path.join(fragmentDir, packName))) {
          const fragments = fs.readdirSync(path.join(fragmentDir, packName));

          // Loop over each file
          fragments.forEach((fragment) => {
            if (DEBUG) {
              log(`DEBUG: Processing ${packName}/${fragment}`);
            }
            const fragmentPath = path.join(fragmentDir, packName, fragment);
            const entry = YAML.load(fs.readFileSync(fragmentPath), "UTF-8");

            _cleanPackData(entry);

            // Because the output for each type of compendia is different
            // we need to construct the items differently for each
            if (packType === "Item") {
              const itemName = entry.name;
              const itemDescription = entry.system.description.value
                ? entry.system.description.value
                : "";

              const item = {
                name: itemName,
                description: itemDescription,
              };

              packData.entries[itemName] = item;
            }

            if (packType === "RollTable") {
              const tableName = entry.name;
              const tableResults = {};

              console.log(entry.results);
              entry.results.forEach((item) => {
                const key = `${item.range[0]}-${item.range[1]}`;
                tableResults[key] = item.text;
              });

              packData.entries[tableName] = {
                name: tableName,
                results: [tableResults],
              };
            }
          });

          fs.writeFileSync(babelePath, JSON.stringify(packData, null, 2));
        }
      }
    });
    log("Finished Generating Babele Files...");
    cb();
  });
}

export { extPacks, genPacks, genPacksBabele };
