/* eslint-disable no-param-reassign  */
import Datastore from "nedb";
import YAML from "js-yaml";
import fs from "fs-extra";
import log from "fancy-log";
import path from "path";
import sanitize from "sanitize-filename";

import * as config from "./config.mjs";
import { DEBUG, SYSTEM_FILE, SYSTEM_NAME } from "./constants.mjs";

const destFolder = path.resolve(config.dataPath);
const srcFolder = "src";

// Make sure we have a nice filename
function _cleanFileName(data) {
  if (DEBUG) {
    log("DEBUG: Cleaning Filename");
  }
  return sanitize(data)
    .replace(/\u2211/g, "")
    .replace(/\u03B2/g, "")
    .replace(/[‘’]/gu, "")
    .replace(/[“”]/gu, "")
    .replace(/['"]/g, "")
    .replace(/[()]/g, "")
    .replace(/[&]/g, "and")
    .replace(/ /g, ".")
    .replace(/\.\./g, ".")
    .replace(/\.-\./g, ".")
    .toLowerCase();
}

// Removes invisible whitespace chars and normalises single and double-quotes.
function _cleanString(str) {
  return str
    .replace(/\u2060/gu, "")
    .replace(/[‘’]/gu, "'")
    .replace(/[“”]/gu, '"');
}

// Remove unwanted flags, permission, and other data
function _cleanPackData(data) {
  // These could probably be generated by src/template.json
  const itemsWithEffects = [
    "armor",
    "clothing",
    "cyberware",
    "criticalInjury",
    "drug",
    "gear",
    "program",
    "weapon",
  ];

  // Delete Foundry keys we don't need
  if ("_stats" in data) {
    delete data._stats;
  }
  if ("folder" in data) {
    delete data.folder;
  }
  if ("origin" in data) {
    delete data.origin;
  }
  if ("ownership" in data) {
    delete data.ownership;
  }
  if ("sort" in data) {
    delete data.sort;
  }
  if ("permission" in data) {
    delete data.permission;
  }

  // Ensure system.source.page is an int
  if (data.system?.source?.page) {
    data.system.source.page = parseInt(data.system.source.page, 10);
  }

  // If an item should have effects
  if (itemsWithEffects.includes(data.type)) {
    // system.revealed should always be true
    data.system.revealed = true;

    // system.usage should always be one of:
    // 'equipped', 'installed', 'rezzed', 'snorted', or 'toggled'
    // never 'carried'
    // use 'equipped' as the default

    // If we're missing the usage key, set it to 'equipped'
    if ("usage" in data.system === false) {
      data.system.usage = "equipped";
    }
    // If system.usage is set to 'owned' set it to 'equipped' instead
    if (data.system.usage === "owned") {
      data.system.usage = "equipped";
    }
  } else {
    delete data.effects;
    delete data.system?.revealed;
    delete data.system?.usage;
  }

  // Sanitize strings
  if (data.name) data.name = _cleanString(data.name);
  if (data.label) data.label = _cleanString(data.label);

  if (data.system?.description?.value) {
    data.system.description.value = _cleanString(data.system.description.value);
  }

  // Remove empty values from system.ammoVariety
  if (data.type === "weapon") {
    const ammo = data.system.ammoVariety;
    const result = ammo.filter((i) => i !== "");
    data.system.ammoVariety = result;
  }

  // Ensure system.amount is an int
  if (data.system?.amount) {
    data.system.amount = parseInt(data.system.amount, 10);
  }

  // Ensure system.price.market is an int
  if (data.system?.price) {
    data.system.price.market = parseInt(data.system.price.market, 10);
  }

  // Ensure system.humanityLoss.static is an int
  if (data.system?.humanityLoss?.static) {
    data.system.humanityLoss.static = parseInt(
      data.system.humanityLoss.static,
      10
    );
  }

  // Run the function over any effects
  if (data.effects) {
    data.effects.forEach((i) => _cleanPackData(i));
  }
  return data;
}

// Export from Foundry Packs to fragments
// Loop over each pack.db in `dataDir/packs` and create a directory for install
// in `src/packs`
async function extPacks() {
  return new Promise((cb) => {
    log("Extracting Packs...");
    const fragmentDir = path.resolve(srcFolder, "packs");
    const packsDir = path.resolve(destFolder, "packs");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    if (fs.existsSync(packsDir)) {
      packs.forEach((pack) => {
        const packName = pack.name;
        const packPath = path.resolve(packsDir, `${packName}.db`);
        if (DEBUG) {
          log(`DEEBUG: Processing ${packName}`);
        }

        // Check the pack exists
        if (fs.existsSync(packPath)) {
          // Check if the output dir exists, if not create it
          if (!fs.existsSync(path.join(fragmentDir, packName))) {
            fs.mkdirSync(path.join(fragmentDir, packName), { mode: 0o755 });
          }

          // Load the pack into nedb
          const db = new Datastore({ filename: packPath, autoload: true });
          db.loadDatabase();

          // Find each entry and output to YAML file in `src/packs`
          db.find({}, (err, entries) => {
            entries.forEach((entry) => {
              const itemName =
                typeof entry.type !== "string"
                  ? _cleanFileName(entry.name)
                  : `${_cleanFileName(entry.type)}.${_cleanFileName(
                      entry.name
                    )}`;
              if (DEBUG) {
                log(`Processing ${itemName}`);
              }
              const data = _cleanPackData(entry);
              const output = YAML.dump(
                data,
                { sortKeys: true, quotingType: '"' },
                2
              );
              fs.writeFileSync(
                path.join(fragmentDir, packName, `${itemName}.yaml`),
                output,
                { mode: 0o644 }
              );
            });
          });
        } else {
          throw Error(`${packPath} does not exist`);
        }
      });
    } else {
      throw Error(`${packsDir} does not exist.`);
    }
    log("Finished Extracting Packs...");
    cb();
  });
}

async function genPacks() {
  return new Promise((cb) => {
    log("Generating Packs...");
    const fragmentDir = path.resolve(srcFolder, "packs");
    const packsDir = path.resolve(destFolder, "packs");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    // Create the packs dir if it doesn't exist.
    if (!fs.existsSync(packsDir)) {
      fs.mkdirSync(packsDir);
    }

    packs.forEach((pack) => {
      const packName = pack.name;
      const packPath = path.resolve(packsDir, `${packName}.db`);
      if (DEBUG) {
        log(`DEBUG: Processing ${packName}`);
      }

      // If the fragment dir exists, do stuff, else error
      if (fs.existsSync(path.join(fragmentDir, packName))) {
        const fragments = fs.readdirSync(path.join(fragmentDir, packName));
        const db = fs.createWriteStream(packPath, { flags: "a", mode: 0o644 });
        const data = [];

        // Loop over each file
        fragments.forEach((fragment) => {
          if (DEBUG) {
            log(`DEBUG: Processing ${packName}/${fragment}`);
          }
          const fragmentPath = path.join(fragmentDir, packName, fragment);
          const entry = YAML.load(fs.readFileSync(fragmentPath), "UTF-8");

          _cleanPackData(entry);
          data.push(entry);
        });
        // Sort the pack
        data.sort((lhs, rhs) => (lhs._id > rhs._id ? 1 : -1));
        // Write each entry to the pack
        for (const entry of data) {
          db.write(`${JSON.stringify(entry)}\n`);
        }
        if (DEBUG) {
          log(`DEBUG: writing ${packPath}`);
        }
        db.end();
      } else {
        throw Error(`${path.join(fragmentDir, packName)} does not exist`);
      }
    });
    log("Finished Generating Packs...");
    cb();
  });
}

// Export from Foundry Packs to Babele files for translation
// Loop over each pack.db in `dataDir/packs` and create babele file for
// translation using crowdin
async function genPacksBabele() {
  return new Promise((cb) => {
    log("Generating Babele Files...");
    // We only care about translating certian pack types
    const translatedPacks = ["Item", "RollTable"];

    const fragmentDir = path.resolve(srcFolder, "packs");
    const babeleDir = path.resolve(srcFolder, "babele", "en");
    const sysFile = JSON.parse(
      fs.readFileSync(path.resolve(srcFolder, SYSTEM_FILE))
    );
    const { packs } = sysFile;

    // Create the packs dir if it doesn't exist.
    if (!fs.existsSync(babeleDir)) {
      fs.mkdirSync(babeleDir);
    }

    packs.forEach((pack) => {
      if (translatedPacks.includes(pack.type)) {
        const packName = pack.name;
        const packFileName = packName;
        const packLabel = pack.label;
        const packType = pack.type;
        const babelePath = path.resolve(
          babeleDir,
          `${SYSTEM_NAME}.${packFileName}.json`
        );
        if (DEBUG) {
          log(`DEBUG: Processing ${packName}`);
        }

        const packData = {
          label: packLabel,
          entries: {},
        };

        // If the fragment dir exists, do stuff, else error
        if (fs.existsSync(path.join(fragmentDir, packName))) {
          const fragments = fs.readdirSync(path.join(fragmentDir, packName));

          // Loop over each file
          fragments.forEach((fragment) => {
            if (DEBUG) {
              log(`DEBUG: Processing ${packName}/${fragment}`);
            }
            const fragmentPath = path.join(fragmentDir, packName, fragment);
            const entry = YAML.load(fs.readFileSync(fragmentPath), "UTF-8");

            _cleanPackData(entry);

            // Because the output for each type of compendia is different
            // we need to construct the items differently for each
            if (packType === "Item") {
              const itemName = entry.name;
              const itemDescription = entry.system.description.value
                ? entry.system.description.value
                : "";

              const item = {
                name: itemName,
                description: itemDescription,
              };

              packData.entries[itemName] = item;
            }

            if (packType === "RollTable") {
              const tableName = entry.name;
              const tableResults = {};

              entry.results.forEach((item) => {
                const key = `${item.range[0]}-${item.range[1]}`;
                tableResults[key] = item.text;
              });

              packData.entries[tableName] = {
                name: tableName,
                results: [tableResults],
              };
            }
          });

          if (DEBUG) {
            console.log(`DEBUG: writing ${babelePath}`);
          }
          fs.writeFileSync(babelePath, JSON.stringify(packData, null, 2));
        }
      }
    });
    log("Finished Generating Babele Files...");
    cb();
  });
}

export { extPacks, genPacks, genPacksBabele };
